version: '3.3'

services:

  influxdb:
    image: influxdb:latest
    hostname: influxdb
    container_name: influxdb
    user: "$UID:$GID"
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb:rw
      - ./volumes/influxdb/config:/etc/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=influx
      - INFLUXDB_ADMIN_PASSWORD=influx
    restart: always

  telegraf:
    image: telegraf:1.11-alpine
    hostname: telegraf
    container_name: telegraf
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    links:
      - influxdb
    ports:
      - "8125:8125/udp"
    volumes:
      - ./volumes/telegraf/config:/etc/telegraf
      - ./config/telegraf/:/etc/telegraf/
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    depends_on:
      - influxdb
    restart: always

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    hostname: chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=influx
      - INFLUXDB_PASSWORD=influx
      - KAPACITOR_URL=http://kapacitor:9092
      - KAPACITOR_USERNAME=influx
      - KAPACITOR_PASSWORD=influx
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf:rw
    depends_on:
      - influxdb
    restart: always

  kapacitor:
    image: kapacitor:latest
    container_name: kapacitor
    hostname: kapacitor
    ports:
      - "9092:9092"
    environment:
      - VIRTUAL_PORT=9092
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    volumes:
      - ./volumes/kapacitor/config:/etc/kapacitor
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
    depends_on:
      - influxdb
    restart: always

  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb
    container_name: influxdb_cli
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: kapacitor
    container_name: kapacitor_cli
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor