version: '3.5'

services:

  rabbitmq:
    container_name: "rabbitmq"
    hostname: localhost
    build:
      context: ./
      dockerfile: Dockerfile
#    volumes:
#      - "./volumes/etc/:/etc/rabbitmq/"
#      - "./volumes/data/:/var/lib/rabbitmq/"
#      - "./volumes/logs/:/var/log/rabbitmq/"
    ports:
      - "5672:5672"
      - "15672:15672"